Deploy script

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -1,7 +1,25 @@
-#!/usr/bin/env bash -eu
+#!/usr/bin/env bash -e
 # Deploy to Bintray
 
 cd "$(dirname "$0")"/..
 
+# Input version number
+[[ "$#" -ne 1 ]] && { echo "Usage: $ deploy <a.b.c>"; exit 1; }
+VERSION="$1"
+
+# Check env vars
+[ -z "$BINTRAY_USER" ] && { echo "Missing env var BINTRAY_USER"; exit 1; }
+[ -z "$BINTRAY_KEY" ]  && { echo "Missing env var BINTRAY_KEY"; exit 1; }
+
+# Variables
+URL="https://$BINTRAY_USER:$BINTRAY_KEY@api.bintray.com"
+
+# Create version
+curl -X POST "$URL/packages/appstax/maven/appstax-java/versions" -H "Content-Type:application/json" -d "{\"name\":\"$VERSION\"}"
+
+# Create release
 mvn -s settings.xml release:prepare
 mvn -s settings.xml release:perform
+
+# Publish release
+curl -X POST "$URL/content/appstax/maven/appstax-java/$VERSION/publish"
